config/routes.rb
Rails.application.routes.draw do
  resources :security_and_privacy_vulnerabilities
  get '/manufacturers', to: 'manufacturers#index'
  resources :manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/products', to: 'products#index'
  resources :products
  get '/security_and_privacy_vulnerabilities', to: 'security_and_privacy_vulnerabilities#index'
  resources :security_and_privacy_vulnerabilities
end

app/controllers/security_and_privacy_vulnerabilities_controller.rb
class SecurityAndPrivacyVulnerabilitiesController < ApplicationController
  before_action :set_security_and_privacy_vulnerability, only: [:show, :edit, :update, :destroy]

  # GET /security_and_privacy_vulnerabilities
  # GET /security_and_privacy_vulnerabilities.json
  def index
    @security_and_privacy_vulnerabilities = SecurityAndPrivacyVulnerability.all
  end

  # GET /security_and_privacy_vulnerabilities/1
  # GET /security_and_privacy_vulnerabilities/1.json
  def show
  end

  # GET /security_and_privacy_vulnerabilities/new
  def new
    @security_and_privacy_vulnerability = SecurityAndPrivacyVulnerability.new
  end

  # GET /security_and_privacy_vulnerabilities/1/edit
  def edit
  end

  # POST /security_and_privacy_vulnerabilities
  # POST /security_and_privacy_vulnerabilities.json
  def create
    @security_and_privacy_vulnerability = SecurityAndPrivacyVulnerability.new(security_and_privacy_vulnerability_params)

    respond_to do |format|
      if @security_and_privacy_vulnerability.save
        format.html { redirect_to @security_and_privacy_vulnerability, notice: 'Security and privacy vulnerability was successfully created.' }
        format.json { render :show, status: :created, location: @security_and_privacy_vulnerability }
      else
        format.html { render :new }
        format.json { render json: @security_and_privacy_vulnerability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /security_and_privacy_vulnerabilities/1
  # PATCH/PUT /security_and_privacy_vulnerabilities/1.json
  def update
    respond_to do |format|
      if @security_and_privacy_vulnerability.update(security_and_privacy_vulnerability_params)
        format.html { redirect_to @security_and_privacy_vulnerability, notice: 'Security and privacy vulnerability was successfully updated.' }
        format.json { render :show, status: :ok, location: @security_and_privacy_vulnerability }
      else
        format.html { render :edit }
        format.json { render json: @security_and_privacy_vulnerability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /security_and_privacy_vulnerabilities/1
  # DELETE /security_and_privacy_vulnerabilities/1.json
  def destroy
    @security_and_privacy_vulnerability.destroy
    respond_to do |format|
      format.html { redirect_to security_and_privacy_vulnerabilities_url, notice: 'Security and privacy vulnerability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security_and_privacy_vulnerability
      @security_and_privacy_vulnerability = SecurityAndPrivacyVulnerability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def security_and_privacy_vulnerability_params
      params.require(:security_and_privacy_vulnerability).permit(:product_id, :CVE_id, :severity, :description, :advisories)
    end
end

app/helpers/security_and_privacy_vulnerabilities_helper.rb
module SecurityAndPrivacyVulnerabilitiesHelper
end

app/views/security_and_privacy_vulnerabilities/_form.html.erb
<%= form_with(model: security_and_privacy_vulnerability, local: true) do |form| %>
  <% if security_and_privacy_vulnerability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(security_and_privacy_vulnerability.errors.count, "error") %> prohibited this security_and_privacy_vulnerability from being saved:</h2>

      <ul>
      <% security_and_privacy_vulnerability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :CVE_id %>
    <%= form.text_field :CVE_id %>
  </div>

  <div class="field">
    <%= form.label :severity %>
    <%= form.text_field :severity %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :advisories %>
    <%= form.text_area :advisories %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/security_and_privacy_vulnerabilities/edit.html.erb
<h1>Editing Security And Privacy Vulnerability</h1>

<%= render 'form', security_and_privacy_vulnerability: @security_and_privacy_vulnerability %>

<%= link_to 'Show', @security_and_privacy_vulnerability %> |
<%= link_to 'Back', security_and_privacy_vulnerabilities_path %>

app/views/security_and_privacy_vulnerabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Security And Privacy Vulnerabilities</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cve</th>
      <th>Severity</th>
      <th>Description</th>
      <th>Advisories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @security_and_privacy_vulnerabilities.each do |security_and_privacy_vulnerability| %>
      <tr>
        <td><%= security_and_privacy_vulnerability.product_id %></td>
        <td><%= security_and_privacy_vulnerability.cve_id %></td>
        <td><%= security_and_privacy_vulnerability.severity %></td>
        <td><%= security_and_privacy_vulnerability.description %></td>
        <td><%= security_and_privacy_vulnerability.advisories %></td>
        <td><%= link_to 'Show', security_and_privacy_vulnerability %></td>
        <td><%= link_to 'Edit', edit_security_and_privacy_vulnerability_path(security_and_privacy_vulnerability) %></td>
        <td><%= link_to 'Destroy', security_and_privacy_vulnerability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Security And Privacy Vulnerability', new_security_and_privacy_vulnerability_path %><br><br>
<%= link_to 'Go to Products Page', products_path %>

app/views/security_and_privacy_vulnerabilities/new.html.erb
<h1>New Security And Privacy Vulnerability</h1>

<%= render 'form', security_and_privacy_vulnerability: @security_and_privacy_vulnerability %>

<%= link_to 'Back', security_and_privacy_vulnerabilities_path %>

app/views/security_and_privacy_vulnerabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @security_and_privacy_vulnerability.product_id %>
</p>

<p>
  <strong>Cve:</strong>
  <%= @security_and_privacy_vulnerability.cve_id %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @security_and_privacy_vulnerability.severity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @security_and_privacy_vulnerability.description %>
</p>

<p>
  <strong>Advisories:</strong>
  <%= @security_and_privacy_vulnerability.advisories %>
</p>
<% @product.security_and_privacy_vulnerabilities.each do |security_and_privacy_vulnerability| %>
  <tr>
    <td><%= security_and_privacy_vulnerability.product_id %></td>
    <td><%= security_and_privacy_vulnerability.cve_id %></td>
    <td><%= security_and_privacy_vulnerability.description %></td>
    <td><%= security_and_privacy_vulnerability.advisories %></td>
    <br><br>
    <td><%= link_to 'Show', security_and_privacy_vulnerability %></td>
    <td><%= link_to 'Edit', edit_security_and_privacy_vulnerability_path(security_and_privacy_vulnerability) %></td>
    <td><%= link_to 'Destroy', security_and_privacy_vulnerability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <br><br>
<% end %>

<%= link_to 'Edit', edit_security_and_privacy_vulnerability_path(@security_and_privacy_vulnerability) %> |
<%= link_to 'Back', security_and_privacy_vulnerabilities_path %>