config/routes.rb
Rails.application.routes.draw do
  resources :security_and_privacy_vulnerabilities
  get '/manufacturers', to: 'manufacturers#index'
  resources :manufacturers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/products', to: 'products#index'
  resources :products
  get '/security_and_privacy_vulnerabilities', to: 'security_and_privacy_vulnerabilities#index'
  resources :security_and_privacy_vulnerabilities
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
 validates :name, presence: true, uniqueness: true
 validates :street_address, presence: true
 validates :city, presence: true
 validates :state, presence: true
 validates :postal_code, presence: true
 validates :postal_code, numericality: { only_integer: true }
 validates :postal_code, length: { is: 5}
 validates :country_or_region, presence: true
 validates :phone,  presence: true
 validates :phone, numericality: { only_integer: true }
 validates :phone, length: { is: 10}
 validates :email, presence: true
 validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
 has_many :products, dependent: :destroy
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: 'Manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :street_address, :city, :state, :postal_code, :country_or_region, :phone, :email)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<%= form_with(model: manufacturer, local: true) do |form| %>
  <% if manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% manufacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :country_or_region %>
    <%= form.text_field :country_or_region %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editing Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manufacturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Country or region</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufacturers.each do |manufacturer| %>
      <tr>
        <td><%= manufacturer.name %></td>
        <td><%= manufacturer.street_address %></td>
        <td><%= manufacturer.city %></td>
        <td><%= manufacturer.state %></td>
        <td><%= manufacturer.postal_code %></td>
        <td><%= manufacturer.country_or_region %></td>
        <td><%= manufacturer.phone %></td>
        <td><%= manufacturer.email %></td>
        <td><%= link_to 'Show', manufacturer %></td>
        <td><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></td>
        <td><%= link_to 'Destroy', manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacturer', new_manufacturer_path %><br><br>
<%= link_to 'Go to Products Page', products_path %>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @manufacturer.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @manufacturer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @manufacturer.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @manufacturer.postal_code %>
</p>

<p>
  <strong>Country or region:</strong>
  <%= @manufacturer.country_or_region %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @manufacturer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @manufacturer.email %>
</p>
<% @manufacturer.products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.barcode %></td>
    <td><%= product.manufacturer_id %></td>
    <br><br>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <br><br>
<% end %>
<%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %> |
<%= link_to 'Back', manufacturers_path %>